### ISSUE TITLE
Only Mojang accounts work

### ISSUE THREAD

**Issue by Phreyr** [Mojang/AccountsClient#12]
Accounts from minecraft.net return no results while Mojang.com accounts work fine.

**Comment by jomo** [comment]
I don't think this is true, can you provide examples?

**Comment by Phreyr** [comment]
> I don't think this is true, can you provide examples?

Sure! `cedeel` is a migrated account and gives the UUID as expected. `Johnny_Tables` is not and doesn't return one.

**Comment by Dinnerbone** [comment]
``` HTTP
POST /profiles/minecraft HTTP/1.1
Host: api.mojang.com
Content-Type: application/json
Content-Length: 27

["Johnny_Tables", "cedeel"]
```

``` JSON
[
  {
    "id": "628fa8ab6599402ab08c5665fe2a36c1",
    "name": "cedeel"
  },
  {
    "id": "da4a1c7f771743db96f827e8b31206dd",
    "name": "Johnny_Tables",
    "legacy": true
  }
]
```

**Comment by jomo** [comment]
Seems to be working, guess this can be closed.

~~btw, @Dinnerbone your avatar is (not) rotated on GitHub :D~~
