### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by KingBowser** [Mojang/AccountsClient#14]
I am currently working on a ban-lookup library for minecraft that I am publishing under the Apache 2 license.

As it stands right now, AccountsClient has no published artifacts, meaning I have to include it in my artifact or submit it as a 3rd-party artifact - both paths concern me in terms of legality.

I would really appreciate it if mojang could apply some manner of OSS license to the project.

**Comment by grum** [comment]
It's not a library. Feel free to take inspiration (or the actual lines) from the code to do what you need to do. There will not be a license added :)

**Comment by KingBowser** [comment]
Ok! Thanks.
