### ISSUE TITLE
Documentation missing (here it is)

### ISSUE THREAD

**Issue by jomo** [Mojang/AccountsClient#5]
# Docuemtnation

(Documentation moved to [the wiki](../wiki))

**Comment by ezfe** [comment]
I'm guessing that 'legacy' is a non migrated account.

**Comment by jomo** [comment]
That would make sense, cannot test now. It won't return this any longer it seems..

**Comment by jomo** [comment]
Update: it's only returned when the account is indeed legacy, and _when_ returned it's always true.

**Comment by ezfe** [comment]
Yup, I'm seeing that

```
Array
(
    [profiles] => Array
        (
            [0] => Array
                (
                    [id] => 61699b2ed3274a019f1e0ea8c3f06bc6
                    [name] => Dinnerbone
                )

            [1] => Array
                (
                    [id] => c41cfcdd82234262b6630c9298aa91a6
                    [name] => HiGuyMBP
                    [legacy] => 1
                )

        )

    [size] => 2
)
```

**Comment by jomo** [comment]
Updated with info about pagination and limits

**Comment by jomo** [comment]
Updated again, responses seem to be cached on the server

**Comment by jomo** [comment]
Updated once again, I noticed there's a `demo` key that seems to be only there when the value is true..
@Dinnerbone / @mollstam mind telling us what this does? :)
Are these system-claimed accounts?

**Comment by jomo** [comment]
And updated again, added **uuid -> name**.

I have some questions/suggestions:

1) why not use proper JSON, like so:

``` JSON
{ 
  "properties": {
    "textures": "value-goes-here"
  }
}
```

2) what is the textures signature good for?

3) why in the world is the textures-value of the JSON object a string that holds a base64 encoded JSON? Coldn't you just put the actual object in the key?

4) why does the textures object repeat half the keys we already have? I assume this is because you join data from two databases, but it doesn't seem to be neccessary to return the data twice.

**Comment by ezfe** [comment]
@jomo I presume that a demo tag represents a demo account (Which yes, do exist).

About the textures, I have no clue why its structured like that.

**Comment by jomo** [comment]
Ah so demo would be a non-premium / unpaid account? I guess that replaces http://minecraft.net/haspaid.jsp?user={name}

**Comment by ezfe** [comment]
That would make sense yes

**Comment by jomo** [comment]
Seems to be correct, made a few tests and this was always the case. Thanks.

**Comment by ezfe** [comment]
Also it would not be the same as haspaid because haspaid doesn't differentiate non existent to demo

**Comment by jomo** [comment]
Yea but the whole thing won't return non-existent accounts anyways ;)
_(There were other ways to check if a user exists though.)_

**Comment by ezfe** [comment]
Some changes have been made. The request should be to

`https://api.mojang.com/profiles/minecraft`

with the data being an array, each entry being a string which is the username like so:

`["ezekielelin","Dinnerbone"]`

**Comment by jomo** [comment]
Sounds like someone has seen my issue  #9 :+1: 
Will try later today, thanks.

**Comment by ezfe** [comment]
aye

**Comment by ezfe** [comment]
Also the data returned is different:

```
[
    {
        "id":"1e6e79ca12a64a25ae0535cfa0ae576d","name":"ezekielelin"
    },
    {
        "id":"61699b2ed3274a019f1e0ea8c3f06bc6","name":"Dinnerbone"
    }
]
```

**Comment by jomo** [comment]
Updated once again, now includes the new API.

**Comment by jessestricker** [comment]
This is great, you should do a pull request either on Readme.MD, the wiki or gh-pages branch!

**Comment by jomo** [comment]
Thanks for the suggestion @Cornyfisch, moved documentation to [the wiki](../wiki)!
