### ISSUE TITLE
Bad design for bulk queries

### ISSUE THREAD

**Issue by jomo** [Mojang/AccountsClient#9]
Why does every user need an agent? This is way more data than required.
Instead of

``` JSON
[
  {"name":"jeb_", "agent": "minecraft"},
  {"name":"Dinnerbone", "agent":"minecraft"}
]
```

it would be much better (saving badwith and time) to use:

``` JSON
[
  {
    "agent": "minecraft",
    "names": ["jeb_", "Dinnerbone"]
  }
]
```

It would still be possible to get usernames for different agents (Scrolls?) in the same request although I can hardly imagine a case where that would happen.

I made a quick test with 50 users and the payload went from 2401 bytes to 938 (!)
The normal payload is more than 2.5 x the size.

Support for this doesn't break the current system, so there's only pros and no cons. :)

**Comment by codename-B** [comment]
This can be closed now :)

**Comment by jomo** [comment]
Indeed.
